name: Katalon Test (Web Service)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      test_suite_path:
        description: 'Optional: Test Suite path (e.g., Test Suites/Smoke.ts)'
        required: false
        default: ''
      execution_profile:
        description: 'Katalon profile to use'
        required: false
        default: 'default'

jobs:
  katalon-test:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    env:
      KATALON_IMAGE: katalonstudio/katalon:latest
      REPORT_DIR: ${{ github.workspace }}/reports

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Katalon project & suite (auto fallback)
        id: detect
        shell: bash
        run: |
          set -e
          PROJ=$(find . -maxdepth 2 -name "*.prj" | head -n1)
          if [ -z "$PROJ" ]; then echo "No .prj file found"; exit 1; fi
          echo "project=$PROJ" >> $GITHUB_OUTPUT
          if [ -n "${{ github.event.inputs.test_suite_path }}" ]; then
            SUITE="${{ github.event.inputs.test_suite_path }}"
          else
            SUITE=$(find "Test Suites" -type f -name "*.ts" | head -n1)
          fi
          if [ -z "$SUITE" ]; then echo "No Test Suite (*.ts) found under 'Test Suites/'"; exit 1; fi
          echo "suite=$SUITE" >> $GITHUB_OUTPUT
          echo "Detected project: $PROJ"
          echo "Using suite:     $SUITE"

      - name: Prepare reports dir
        run: mkdir -p "$REPORT_DIR"

      - name: Pull Katalon image
        run: docker pull $KATALON_IMAGE

      - name: Run Katalon (Web Service)
        env:
          KATALON_API_KEY: ${{ secrets.KATALON_API_KEY }}
        run: |
          docker run --rm \
            -e KATALON_API_KEY="$KATALON_API_KEY" \
            -v "${{ github.workspace }}":/katalon/katalon/source:ro \
            -v "$REPORT_DIR":/katalon/katalon/report \
            $KATALON_IMAGE \
            katalonc -noSplash -runMode=console -consoleLog -retry=0 \
              -projectPath="/katalon/katalon/source/${{ steps.detect.outputs.project }}" \
              -testSuitePath="${{ steps.detect.outputs.suite }}" \
              -executionProfile="${{ github.event.inputs.execution_profile }}" \
              -browserType="Web Service" \
              -reportFolder="/katalon/katalon/report" \
              -enableLicenseRetry -retry=3 -retryFailedTestCases=false

      - name: Upload reports (HTML/JUnit/XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: katalon-reports
          path: |
            ${{ env.REPORT_DIR }}/
            **/JUnit_Report.xml
          if-no-files-found: warn
          retention-days: 7
